FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -o backend ./cmd

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/backend .

EXPOSE 8080

ENTRYPOINT ["./backend"]
